vcs:
  type: git
agents:
  available:
  - copilot
  - claude
  - gemini
  - cursor
  - codex
  selection:
    strategy: preferred
    preferred_implementer: copilot
    preferred_reviewer: codex
project:
  uuid: 8a4a7da6-a97c-4bb4-893a-b31664abfee4
  slug: spec-kitty
  node_id: d036a097a835
